# NumPy Tutorial

NumPy is one of the most used package in Python. It provides multidimenional array object and all sorts of routine for operations on arrays. 
We will only scratch the surface of what NumPy is capable of in this tutorial. You can check out [their website](https://docs.scipy.org/doc/numpy/index.html) for more information.

A good amount of the material in this notebook comes from:
* [CS231n Python & NumPy Tutorial by Justin Johnson](http://cs231n.github.io/python-numpy-tutorial/)
* [NumPy Quickstart Tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html)

## For those that are familiar with Matlab

Matlab and NumPy/SciPy have a lot in common. But there also many differences. We recommend you read the [Numpy for Matlab users webpage](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html).

## Prequisite

In [1]:
import numpy as np

## The Basics

The main object in NumPy is `ndarray`. It is a table of elements (usually numbers), all of the same type. In NumPy dimensions are called _axes_. Here are some important attributes of `ndarray`:

* ndarray.ndim: The number of dimensions of the array.
* ndarray.shape: The dimensions of the array.
* ndarray.size: The total number of elements of the array.
* ndarray.dtype: The type of the elements in the array.

Here is an exmaple

In [32]:
a = np.array([[1, 2, 3],[4, 5, 6]])
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.size)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int64
6


## Array creation

There are various ways to create NumPy arrays:

In [33]:
a = np.array([[1, 2, 3],[4, 5, 6]])    # Create by lists
b = np.zeros((2, 2))    # Create an array full of zeros with dimension (2, 2)
c = np.ones((3, ))    # Create an array full of ones with dimension (3, )
d = np.arange(0, 10, 2)   # Create 1-d array from 0 to 10 spaced with 2
e = np.random.random((3, 3))    # Create an array full of random numbers with dimension (3, 3)
print(a, '\n')
print(b, '\n')
print(c, '\n')
print(d, '\n')
print(e, '\n')

[[1 2 3]
 [4 5 6]] 

[[0. 0.]
 [0. 0.]] 

[1. 1. 1.] 

[0 2 4 6 8] 

[[0.26456932 0.55416868 0.31622063]
 [0.12763405 0.88360159 0.59699571]
 [0.28773449 0.49498605 0.88727801]] 



## Array operation/math

NumPy performs element-wise operation on default.

In [34]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print(x + y, '\n')
print(x - y, '\n')
print(x * y, '\n')
print(x / y, '\n')
print(x ** 2, '\n')

[[ 6  8]
 [10 12]] 

[[-4 -4]
 [-4 -4]] 

[[ 5 12]
 [21 32]] 

[[0.2        0.33333333]
 [0.42857143 0.5       ]] 

[[ 1  4]
 [ 9 16]] 



Matrix/Vector inner product is perform by `np.dot()`

In [35]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
a = np.array([9, 0])
b = np.array([1, 2])
print(np.dot(x, y))
print(np.dot(a, b))
print(np.dot(x, a))

[[19 22]
 [43 50]]
9
[ 9 27]


There are many other useful function in NumPy, to name a few:

In [36]:
x = np.array([[1, 2, 3], 
              [4, 5, 6]])
print(np.sum(x))          # Compute sum of all elements
print(np.sum(x, axis=0))  # Compute sum of each column
print(np.sum(x, axis=1), '\n')  # Compute sum of each row

print(np.max(x, axis=1))  # Compute max of each row
print(x.max(1), '\n')    # Same as the line above

print(np.min(x, axis=-1))  # Compute min according to last dimension
print(np.mean(x, axis=0), '\n')  # Compute mean according of each column

21
[5 7 9]
[ 6 15] 

[3 6]
[3 6] 

[1 4]
[2.5 3.5 4.5] 



Note the axis you apply the operation will have its dimension removed from the shape. This is useful to keep in mind when you're trying to figure out what axis corresponds to what.

How can we compute the index of the max value of each row?

In [37]:
x = np.array([[1, 2, 3], 
              [4, 5, 6]])
print(np.argmax(x, axis=1)) # Compute index of max of each row

[2 2]


Sometimes we want to convert dtype of an entire array, we can:

In [38]:
x = np.array([[1, 2, 3], 
              [4, 5, 6]])
print(x.astype('float'))

[[1. 2. 3.]
 [4. 5. 6.]]


`np.meshgrid` methods help create coordinate matrices from coordinate vectors


In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
xv,yv = np.meshgrid(x,y)
print(xv) 
print(yv) 

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[4 4 4]
 [5 5 5]
 [6 6 6]]


`np.any` and `np.all` can test whether an array element (along a given axis) evaluates to True.

In [ ]:
x = np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]])

print("x > 3:\n", x > 3)
print("np.any(x > 3):\n", np.any(x > 3))  # True, since 4 and 5 > 3
print("np.all(x > 3):\n", np.all(x > 3))  # False, not all elements > 3
print("np.any(x > 3, axis=1):\n", np.any(x > 3, axis=0))  # Any non-zero in each row
print("np.all(x > 3, axis=1):\n", np.all(x > 3, axis=1))  # All non-zero in each row

## np.linalg
The **numpy.linalg** module provides linear algebra functions in Python using NumPy.  
It helps you solve systems of equations, compute matrix properties, and perform operations such as matrix inversion and eigenvalue decomposition.   

In [11]:
# Solving linear systems (Ax = b)  

A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

x = np.linalg.solve(A, b)
print("Solution x:\n", x)

Solution x:
 [2. 3.]


In [12]:
# Computing matrix inverse or determinant 

A = np.array([[4, 7], [2, 6]])
A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)

Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [13]:
# Eigenvalues and eigenvectors  

A = np.array([[2, 0], [0, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]


There are many more usefule NumPy functions. We don't need to memorize all of them, because we can always google it! :)

## Indexing, Slicing

NumPy arrays can be indexed, sliced much like lists in Python.

In [39]:
a = np.arange(100)
print(a)
print(a[2])
print(a[-1])    # Retrieve last element
print(a[2:5])
print(a[:5])
print(a[90:])
print(a[:50:10])    # Retrieve from a[0:50], but sample every 10 elements
print(a[::-10])    # Sample every 10 elements, but in reverse order

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
2
99
[2 3 4]
[0 1 2 3 4]
[90 91 92 93 94 95 96 97 98 99]
[ 0 10 20 30 40]
[99 89 79 69 59 49 39 29 19  9]


Same method applys to multidimensional arrays.

In [40]:
b = np.random.randint(0, 10, (5, 5))
print(b)
print(b[0, 3])
print(b[:, 3])
print(b[1:3, :])
print(b[0])    # Indexing first dimension

[[7 0 0 3 3]
 [5 0 2 3 8]
 [9 4 8 8 6]
 [4 3 0 1 0]
 [0 5 4 0 9]]
3
[3 3 8 1 0]
[[5 0 2 3 8]
 [9 4 8 8 6]]
[7 0 0 3 3]


Sometimes the array dimension is large. The __dots__ (`...`) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then
* `x[1, 2, ...]` is equivalent to `x[1,2,:,:,:]`
* `x[...,3]` to `x[:,:,:,:,3]`
* `x[4,...,5,:]` to `x[4,:,:,5,:]`

NumPy also supports indexing with ndarray, in two fashion: integer array, boolean array. This is also called fancy indexing.

In [41]:
a = np.random.randint(0, 10, (5, 5))
b = [0, 2, 4]
a[b, :] = 0    # Index with integer array
print(a, '\n')
c = a > 5     
a[c] = 10    # Index with boolean array
print(c, '\n')
print(a, '\n')

[[0 0 0 0 0]
 [5 1 0 6 9]
 [0 0 0 0 0]
 [3 4 2 1 4]
 [0 0 0 0 0]] 

[[False False False False False]
 [False False False  True  True]
 [False False False False False]
 [False False False False False]
 [False False False False False]] 

[[ 0  0  0  0  0]
 [ 5  1  0 10 10]
 [ 0  0  0  0  0]
 [ 3  4  2  1  4]
 [ 0  0  0  0  0]] 



## Shape manimulation

There are also functions that manipulate shape of an array in NumPy. For example:

In [42]:
a = np.random.randint(10, size=(3, 4))
print(a)
print(a.shape, '\n')

print(a.flatten(), '\n')    # Flatten the array
print(a.reshape(6, 2), '\n')    # Reshape the array to shape (6, 2)
print(a.reshape(6, -1), '\n')    # If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
print(a.T, '\n')    # Transpose the array

[[5 0 2 4]
 [3 2 8 6]
 [5 3 6 5]]
(3, 4) 

[5 0 2 4 3 2 8 6 5 3 6 5] 

[[5 0]
 [2 4]
 [3 2]
 [8 6]
 [5 3]
 [6 5]] 

[[5 0]
 [2 4]
 [3 2]
 [8 6]
 [5 3]
 [6 5]] 

[[5 3 5]
 [0 2 3]
 [2 8 6]
 [4 6 5]] 



NumPy can also stack/concatenate arrays:

In [43]:
a = np.random.randint(10, size=(3, 4))
b = np.random.randint(10, size=(3, 4))
print(np.concatenate((a, b), axis=0).shape)    # Concatenate arrays on the first dimension
print(np.concatenate((a, b), axis=-1).shape)    # Concatenate arrays on the last dimension
print(np.stack((a, b), axis=0).shape)    # Prepends array dimension, then concatenate arrays on the first dimension
print(np.stack((a, b), axis=-1).shape)    # Append array dimension, then concatenate arrays on the last dimension

(6, 4)
(3, 8)
(2, 3, 4)
(3, 4, 2)


Also, there are quick ways to expand an array with a dummy dimension or reduce an array's dummy dimension.

In [44]:
a = np.random.randint(10, size=(5, 6))
a = np.expand_dims(a, axis=0)
print(a.shape)    # Expand array dimension by prepending a dimension
a = np.expand_dims(a, axis=-1)
print(a.shape)    # Expand array dimension by appending a dimension

print(np.squeeze(a).shape)    # Reduce all dummy dimensions
print(np.squeeze(a, axis=0).shape)    # Reduce a specific dimension

(1, 5, 6)
(1, 5, 6, 1)
(5, 6)
(5, 6, 1)


## Broadcasting

Many of the operations we've looked at above involved arrays of the same rank.
However, many times we might have a smaller array and use that multiple times to update an array of a larger rank.
For example, consider the below example of shifting the mean of each column from the elements of the corresponding column:

In [45]:
x = np.array([[1, 2, 3],
              [3, 5, 7]])
print(x.shape)

col_means = x.mean(axis=0)
print(col_means)
print(col_means.shape)    # col_means has a smaller rank than x!

mean_shifted = x - col_means    # col_means automatically expands dimension
print('\n', mean_shifted)
print(mean_shifted.shape)

(2, 3)
[2.  3.5 5. ]
(3,)

 [[-1.  -1.5 -2. ]
 [ 1.   1.5  2. ]]
(2, 3)


Or even just multiplying a matrix by 2:

In [46]:
x = np.array([[1, 2, 3],
              [3, 5, 7]])
print(x * 2)


[[ 2  4  6]
 [ 6 10 14]]


Broadcasting two arrays together follows these rules:
1. If the arrays do not have the same rank, __prepend__ the shape of the lower rank array with __1s__ until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or __if one of the arrays has size 1 in that dimension__.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were __copied along that dimension__.

For example, when subtracting the columns above, we had arrays of shape (2, 3) and (3,).
1. These arrays do not have same rank, so we prepend the shape of the lower rank one to make it (1, 3).
2. (2, 3) and (1, 3) are compatible (have the same size in the dimension, or if one of the arrays has size 1 in that dimension).
3. Can be broadcast together!
4. After broadcasting, each array behaves as if it had shape equal to (2, 3).
5. The smaller array will behave as if it were copied along dimension 0.

Let's try to subtract the mean of each row!

In [47]:
x = np.array([[1, 2, 3],
              [3, 5, 7]])
row_means = x.mean(axis=1)
print(row_means)
mean_shifted = x - row_means

[2. 5.]


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

What happened?

Answer: If we following broadcasting rule 1, then we'd prepend a 1 to the smaller rank array ot get (1, 2). However, the last dimensions don't match now between (2, 3) and (1, 2), and so we can't broadcast.

Take 2, reshaping the row means to get the desired behavior:

In [48]:
x = np.array([[1, 2, 3],
              [3, 5, 7]])
print(x.shape)

row_means = x.mean(axis=1).reshape((-1, 1))
print(row_means)
print(row_means.shape)

mean_shifted = x - row_means
print(mean_shifted)
print(mean_shifted.shape) 

(2, 3)
[[2.]
 [5.]]
(2, 1)
[[-1.  0.  1.]
 [-2.  0.  2.]]
(2, 3)


## Views vs. Copies

Unlike a copy, in a **view** of an array, the data is shared between the view and the array. Sometimes, our results are copies of arrays, but other times they can be views. Understanding when each is generated is important to avoid any unforeseen issues.

Views can be created from a slice of an array, changing the dtype of the same data area (using arr.view(dtype), not the result of arr.astype(dtype)), or even both.

In [49]:
x = np.arange(5)
print('Original:\n', x)

# Modifying the view will modify the array
view = x[1:3]
view[1] = -1
print('Array After Modified View:\n', x)

Original:
 [0 1 2 3 4]
Array After Modified View:
 [ 0  1 -1  3  4]


However, if we use fancy indexing, the result will actually be a copy and not a view:

In [50]:
x = np.arange(5)
print('Original:\n', x)

# Modifying the result of the selection due to fancy indexing
# will not modify the original array.
copy = x[[1, 2]]
copy[1] = -1
print('Copy:\n', copy)
print('Array After Modified Copy:\n', x)

Original:
 [0 1 2 3 4]
Copy:
 [ 1 -1]
Array After Modified Copy:
 [0 1 2 3 4]


In [51]:
# Another example involving fancy indexing
x = np.arange(5)
print('Original:\n', x)

copy = x[x >= 2]
print('Copy:\n', copy)
x[3] = 10
print('Modified Array:\n', x)
print('Copy After Modified Array:\n', copy)

Original:
 [0 1 2 3 4]
Copy:
 [2 3 4]
Modified Array:
 [ 0  1  2 10  4]
Copy After Modified Array:
 [2 3 4]


## np.linalg
The **numpy.linalg** module provides linear algebra functions in Python using NumPy.  
It helps you solve systems of equations, compute matrix properties, and perform operations such as matrix inversion and eigenvalue decomposition.   

# Speed 

In [27]:
def shrink(array):
    output = np.empty(len(array))
    for i in range(len(array)):
        output[i] = array[i] / 2
    return output

In [30]:
import time

W,H = 1920,1080
array = np.random.rand(W*H)

%timeit shrink(array)
%timeit array/2

t0 = time.time()
shrink(array)
t1 = time.time()
array/2
t2 = time.time()
print('FPS :', int(1/(t1-t0)),'/',int(1/(t2-t1)))


454 ms ± 4.19 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.79 ms ± 25 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
FPS : 2 / 427


## Last Tips

* NumPy is an incredibly powerful library for computation providing both massive efficiency gains and convenience.
* There still lots of NumPy functions not covered in this tutorial. So don't afraid to consult Google!
* Always keep track of array shapes. Especially, NumPy automatically squeeze arrays after most functions.
* Watch out for views & copies.
* The speed of fancy indexing (integer array indexing vs. boolean array indexing) can differs a lot when processing large arrays.